#AndroidCS: enforce UTF-8 & locale for Gradle daemon
#Tue Aug 11 02:02:22 GMT 2026
android.disableAutomaticLintVital=true
android.enablePublishCheck=false
android.javaCompile.suppressSourceTargetDeprecationWarning=true
android.lint.checkReleaseBuilds=false
android.lint.enableVital=false
android.lint.enabled=false
android.suppressUnsupportedCompileSdk=36
android.useAndroidX=true
compileSdkVersion=36
markwonVersion=4.6.2
minSdkVersion=21
ndkVersion=29.0.14033849
org.gradle.daemon=true
org.gradle.daemon.idletimeout=10800000
org.gradle.jvmargs=-Xmx8192M -Dfile.encoding\=UTF-8 -Dsun.jnu.encoding\=UTF-8 -Duser.language\=en -Duser.country\=US
org.gradle.parallel=true
systemProp.file.encoding=UTF-8
systemProp.sun.jnu.encoding=UTF-8
systemProp.user.country=US
systemProp.user.language=en
targetSdkVersion=28
