package com.UIN.Tool.proot

import com.UIN.Tool.log.Logger
import java.io.File
import java.io.FileOutputStream

/**
 * Post-extraction rootfs setup helpers.
 * Modeled after proot-distro's helpers/rootfs.py.
 */
object RootfsSetup {

    private const val TAG = "RootfsSetup"

    private const val RESOLV_CONF = """# Generated by UIN Tool
nameserver 8.8.8.8
nameserver 8.8.4.4
"""

    private const val HOSTS = """# IPv4.
127.0.0.1   localhost.localdomain localhost

# IPv6.
::1         localhost.localdomain localhost ip6-localhost ip6-loopback
fe00::0     ip6-localnet
ff00::0     ip6-mcastprefix
ff02::1     ip6-allnodes
ff02::2     ip6-allrouters
ff02::3     ip6-allhosts
"""

    /**
     * Run all post-extraction rootfs fixups.
     */
    fun setup(rootfsDir: File): Boolean {
        try {
            Logger.i(TAG, "Running post-extraction rootfs setup...")

            // Write /etc/resolv.conf
            writeResolvConf(rootfsDir)

            // Write /etc/hosts
            writeHosts(rootfsDir)

            // Create /tmp with correct permissions
            val tmpDir = File(rootfsDir, "tmp")
            if (!tmpDir.exists()) {
                tmpDir.mkdirs()
            }
            Runtime.getRuntime().exec(arrayOf("chmod", "1777", tmpDir.absolutePath)).waitFor()

            // Create /var/tmp
            val varTmpDir = File(rootfsDir, "var/tmp")
            if (!varTmpDir.exists()) {
                varTmpDir.mkdirs()
            }
            Runtime.getRuntime().exec(arrayOf("chmod", "1777", varTmpDir.absolutePath)).waitFor()

            // Create /root directory
            val rootDir = File(rootfsDir, "root")
            if (!rootDir.exists()) {
                rootDir.mkdirs()
            }
            Runtime.getRuntime().exec(arrayOf("chmod", "700", rootDir.absolutePath)).waitFor()

            Logger.i(TAG, "Post-extraction rootfs setup complete")
            return true
        } catch (e: Exception) {
            Logger.e(TAG, "Failed to setup rootfs", e)
            return false
        }
    }

    private fun writeResolvConf(rootfsDir: File) {
        val etcDir = File(rootfsDir, "etc")
        if (!etcDir.exists()) {
            etcDir.mkdirs()
        }
        val file = File(etcDir, "resolv.conf")
        try {
            FileOutputStream(file).use { fos ->
                fos.write(RESOLV_CONF.toByteArray())
            }
            Logger.d(TAG, "Written /etc/resolv.conf")
        } catch (e: Exception) {
            Logger.e(TAG, "Failed to write resolv.conf", e)
        }
    }

    private fun writeHosts(rootfsDir: File) {
        val etcDir = File(rootfsDir, "etc")
        if (!etcDir.exists()) {
            etcDir.mkdirs()
        }
        val file = File(etcDir, "hosts")
        try {
            FileOutputStream(file).use { fos ->
                fos.write(HOSTS.toByteArray())
            }
            Logger.d(TAG, "Written /etc/hosts")
        } catch (e: Exception) {
            Logger.e(TAG, "Failed to write hosts", e)
        }
    }
}
